### ISSUE TITLE
[Corretivo] Seleção de novo arquivo de Config duplica extensão

### ISSUE THREAD

**Issue by Gecislaine** [mathsantosilva/MSS#22]
PRÉ CONDIÇÃO
Não há

PASSOS:
1. Executar o MSS
2. Clicar em "Novo arquivo Config"
3. Adicionar o "nome do arquivo" sem extensão
4. Clicar em "Criar"

RESULTADO OBTIDO
O arquivo é gerado com a extensão .json duplicada

RESULTADO ESPERADO
O arquivo é gerado apenas com a extensão delimitante de funcionamento

EVIDENCIA
![2023-09-22_10-01-28](https://github.com/mathsantosilva/MSS/assets/40772055/7d166c8c-598b-4a59-9f50-d3f8e7c88576)

**Comment by mathsantosilva** [comment]
Entregue no commit ac39128
Liberado na release 3.4.2
