### ISSUE TITLE
[Corretivo] Configuração de Aparencia é perdida na seleção de opções

### ISSUE THREAD

**Issue by Gecislaine** [mathsantosilva/MSS#24]
Configuração de aparência é perdida na seleção de opções de arquivo de config

PRE CONDIÇÃO
Possuir aparencia configurada diferente da padrão

PASSOS
1. Acessar o MSS, em "Configuração"
2. Clicar sobre um dos botões de escolha

RESULTADO OBTIDO
Botão volta a cor padrão

RESULTADO ESPERADO
Botão mantém a cor pré-definida no menu "Aparência" 

EVIDENCIA
![2023-09-22_10-45-20](https://github.com/mathsantosilva/MSS/assets/40772055/b2e78fb1-1567-4d57-ae6a-54a4278bedb5)

**Comment by mathsantosilva** [comment]
Liberado na versão 3.5.0
